WANDB_MODE: "disabled"
ENTITY: ""
PROJECT: ""
RUN_NAME: "test-ckpt"
OUTPUT_DIR: ""

ENV_NAME: "Craftax-Coop-Symbolic"
MAX_PASSIVE_MOBS: 5
MAX_MELEE_MOBS: 2
MAX_RANGED_MOBS: 0

DISABLE_REVIVE: false
REVIVING_COOLDOWN_STEPS: 50
ACTION_MASK_WHILE_DEAD: true

SHARED_REWARD: true

TEAMMATE_ALIVE_BONUS: 0.05
ALL_TEAM_ALIVE_BONUS: 0.2
DEAD_SELF_PENALTY_WEIGHT: 0.2
ONE_TIME_DEATH_PENALTY_SHARED: 0.0
ONE_TIME_DEATH_PENALTY_INDIVIDUAL: 0.0
WARRIOR_MELEE_KILL_REWARD: 7.5
WARRIOR_PASSIVE_FOOD_GAIN: 1
FORAGER_PASSIVE_FOOD_GAIN: 3
FORAGER_FOOD_CAPACITY: 27
FORAGER_TO_WARRIOR_FOOD_TRADE_REWARD: 1.0
FORAGER_TO_WARRIOR_DRINK_TRADE_REWARD: 1.0

ENABLE_AUTO_RESPAWNING: false
AUTO_RESPAWN_STEPS: 50
RESTRICT_AUTO_RESPAWNING_TO_SPAWN_ROOM: true

TRADE_RADIUS: 15
TRADE_RADIUS_SHAPE: "circle"

EARLY_EPISODE_CAP: 0
EARLY_EPISODE_CAP_UNTIL: 0
GENERAL_EPISODE_CAP: 0
TERMINATE_ON_ANY_DEATH: false
TERMINATE_ON_ANY_DEATH_OFFSET: 800

NUM_TEAMS: 1
TEAM_COMPOSITION: [1, 2]
USE_REDUCED_ACTION_SPACE: true

ALG_NAME: "ippo-rnn"
GRU_HIDDEN_DIM: 8
FC_DIM_SIZE: 8
ACTIVATION: "tanh"

TOTAL_TIMESTEPS: 176
NUM_ENVS: 4
NUM_STEPS: 4
NUM_MINIBATCHES: 2
UPDATE_EPOCHS: 1
GAE_LAMBDA: 0.8
GAMMA: 0.99
CLIP_EPS: 0.2
SCALE_CLIP_EPS: false
ENT_COEF: 0.01
VF_COEF: 0.5
AUX_COEF: 0.1
USE_TEAMMATE_AUXILIARY_LOSS: false
AUX_TEAMMATE_WEIGHT: 0.3333
ANNEAL_LR: true
LR: 0.0002
MAX_GRAD_NORM: 1.0
LR_WARMUP: 0.0
REW_SHAPING_HORIZON: 1000000

NUM_SEEDS: 1
SEED: 0

LOGGING_UPDATES_INTERVAL: 2
LOGGING_NUM_CALLS: 1
LOGGING_STEPS_PER_CALL: 8
LOGGING_THREADS: 1

SAVE_VIDEO: false
VIDEO_LENGTH: 16
VIDEO_PIXEL_SIZE: 16
SAVE_HIDDEN_STATES: false

CHECKPOINTING: true
CHECKPOINT_DIR: ""
CHECKPOINT_INTERVAL_BLOCKS: 1
CHECKPOINT_MAX_TO_KEEP: 3
RESUME: "auto"
MAX_BLOCKS_THIS_RUN: 0
